notifications:
  email: false
  slack: false

language: go

env:
  - GO111MODULE=on

go:
  - "1.14.x"
  - "1.15.x"
  - "1.16.x"

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.38.0

script:
  - make install
  - make ls-lint
  - make linter
  - go run examples/basic.go